version: '2'
services:
  db:
    image: mongo:latest
    container_name: db # if you check the db.js file we're connecting to mongoose client using 'db' instead of 'localhost'
    networks:
      - todonet
  web:
    build: ../.
    networks:
      - todonet
    ports:
     - "3000"
networks:
  todonet: 
    driver: bridge